//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string Member_ID { get; set; }
        public string Member_Name { get; set; }
        public string Member_Date { get; set; }
        public string Member_Email { get; set; }
        public string Package_ID { get; set; }
        public string DietPlanID { get; set; }
        public string Member_sex { get; set; }
        public Nullable<System.DateTime> Member_PackageExpiry { get; set; }
        public string AddedBy { get; set; }
        public string Trainer_ID { get; set; }
    
        public virtual Diet_Plan Diet_Plans { get; set; }
        public virtual Package Package { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual User User { get; set; }
    }
}
